# 100 companies curated for a UIUC Computer Engineering senior targeting
# software and/or hardware roles. 20 per day, grouped thematically:
# Day 1: Big Tech / Software   Day 2: Semiconductor / Hardware
# Day 3: Aerospace / Defense / Automotive   Day 4: Quant Trading / Fintech
# Day 5: Illinois-region recruiters + AI / misc

PLANNER_COMPANIES = [
    # ── Day 1: Big Tech / Software ──────────────────────────────────────
    {"name": "Google",              "industry": "Big Tech / Software",
     "career_url": "https://careers.google.com/",
     "linkedin_url": "https://www.linkedin.com/company/google/jobs/"},
    {"name": "Microsoft",           "industry": "Big Tech / Software",
     "career_url": "https://careers.microsoft.com/",
     "linkedin_url": "https://www.linkedin.com/company/microsoft/jobs/"},
    {"name": "Amazon",              "industry": "Big Tech / Software",
     "career_url": "https://www.amazon.jobs/en/",
     "linkedin_url": "https://www.linkedin.com/company/amazon/jobs/"},
    {"name": "Meta",                "industry": "Big Tech / Software",
     "career_url": "https://www.metacareers.com/",
     "linkedin_url": "https://www.linkedin.com/company/meta/jobs/"},
    {"name": "Apple",               "industry": "Big Tech / Software",
     "career_url": "https://jobs.apple.com/en-us/search",
     "linkedin_url": "https://www.linkedin.com/company/apple/jobs/"},
    {"name": "Oracle",              "industry": "Big Tech / Software",
     "career_url": "https://www.oracle.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/oracle/jobs/"},
    {"name": "Salesforce",          "industry": "Big Tech / Software",
     "career_url": "https://www.salesforce.com/company/careers/",
     "linkedin_url": "https://www.linkedin.com/company/salesforce/jobs/"},
    {"name": "Adobe",               "industry": "Big Tech / Software",
     "career_url": "https://www.adobe.com/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/adobe/jobs/"},
    {"name": "Cisco",               "industry": "Big Tech / Software",
     "career_url": "https://jobs.cisco.com/",
     "linkedin_url": "https://www.linkedin.com/company/cisco/jobs/"},
    {"name": "ServiceNow",          "industry": "Big Tech / Software",
     "career_url": "https://careers.servicenow.com/",
     "linkedin_url": "https://www.linkedin.com/company/servicenow/jobs/"},
    {"name": "SAP",                 "industry": "Big Tech / Software",
     "career_url": "https://jobs.sap.com/",
     "linkedin_url": "https://www.linkedin.com/company/sap/jobs/"},
    {"name": "Dell Technologies",   "industry": "Big Tech / Software",
     "career_url": "https://jobs.dell.com/",
     "linkedin_url": "https://www.linkedin.com/company/dell-technologies/jobs/"},
    {"name": "HP Inc.",             "industry": "Big Tech / Software",
     "career_url": "https://jobs.hp.com/",
     "linkedin_url": "https://www.linkedin.com/company/hp/jobs/"},
    {"name": "IBM",                 "industry": "Big Tech / Software",
     "career_url": "https://www.ibm.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/ibm/jobs/"},
    {"name": "Uber",                "industry": "Big Tech / Software",
     "career_url": "https://www.uber.com/us/en/careers/",
     "linkedin_url": "https://www.linkedin.com/company/uber-com/jobs/"},
    {"name": "Lyft",                "industry": "Big Tech / Software",
     "career_url": "https://www.lyft.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/lyft/jobs/"},
    {"name": "Airbnb",              "industry": "Big Tech / Software",
     "career_url": "https://careers.airbnb.com/",
     "linkedin_url": "https://www.linkedin.com/company/airbnb/jobs/"},
    {"name": "LinkedIn",            "industry": "Big Tech / Software",
     "career_url": "https://careers.linkedin.com/",
     "linkedin_url": "https://www.linkedin.com/company/linkedin/jobs/"},
    {"name": "Netflix",             "industry": "Big Tech / Software",
     "career_url": "https://jobs.netflix.com/",
     "linkedin_url": "https://www.linkedin.com/company/netflix/jobs/"},
    {"name": "Snowflake",           "industry": "Big Tech / Software",
     "career_url": "https://careers.snowflake.com/",
     "linkedin_url": "https://www.linkedin.com/company/snowflake-computing/jobs/"},

    # ── Day 2: Semiconductor / Hardware ─────────────────────────────────
    {"name": "NVIDIA",              "industry": "Semiconductor / Hardware",
     "career_url": "https://www.nvidia.com/en-us/about-nvidia/careers/",
     "linkedin_url": "https://www.linkedin.com/company/nvidia/jobs/"},
    {"name": "Intel",               "industry": "Semiconductor / Hardware",
     "career_url": "https://jobs.intel.com/en/",
     "linkedin_url": "https://www.linkedin.com/company/intel-corporation/jobs/"},
    {"name": "AMD",                 "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.amd.com/",
     "linkedin_url": "https://www.linkedin.com/company/amd/jobs/"},
    {"name": "Qualcomm",            "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.qualcomm.com/",
     "linkedin_url": "https://www.linkedin.com/company/qualcomm/jobs/"},
    {"name": "Texas Instruments",   "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.ti.com/",
     "linkedin_url": "https://www.linkedin.com/company/texas-instruments/jobs/"},
    {"name": "Broadcom",            "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.broadcom.com/",
     "linkedin_url": "https://www.linkedin.com/company/broadcom/jobs/"},
    {"name": "Micron Technology",   "industry": "Semiconductor / Hardware",
     "career_url": "https://www.micron.com/about/careers",
     "linkedin_url": "https://www.linkedin.com/company/micron-technology/jobs/"},
    {"name": "Western Digital",     "industry": "Semiconductor / Hardware",
     "career_url": "https://jobs.westerndigital.com/",
     "linkedin_url": "https://www.linkedin.com/company/western-digital/jobs/"},
    {"name": "Analog Devices",      "industry": "Semiconductor / Hardware",
     "career_url": "https://www.analog.com/en/about-adi/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/analog-devices/jobs/"},
    {"name": "Marvell Technology",  "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.marvell.com/",
     "linkedin_url": "https://www.linkedin.com/company/marvell-technology/jobs/"},
    {"name": "Applied Materials",   "industry": "Semiconductor / Hardware",
     "career_url": "https://jobs.appliedmaterials.com/",
     "linkedin_url": "https://www.linkedin.com/company/applied-materials/jobs/"},
    {"name": "Lam Research",        "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.lamresearch.com/",
     "linkedin_url": "https://www.linkedin.com/company/lam-research/jobs/"},
    {"name": "KLA Corporation",     "industry": "Semiconductor / Hardware",
     "career_url": "https://www.kla.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/kla-corporation/jobs/"},
    {"name": "Synopsys",            "industry": "Semiconductor / Hardware",
     "career_url": "https://www.synopsys.com/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/synopsys/jobs/"},
    {"name": "Cadence Design Systems", "industry": "Semiconductor / Hardware",
     "career_url": "https://www.cadence.com/en_US/home/company/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/cadence-design-systems/jobs/"},
    {"name": "Arm",                 "industry": "Semiconductor / Hardware",
     "career_url": "https://careers.arm.com/",
     "linkedin_url": "https://www.linkedin.com/company/arm/jobs/"},
    {"name": "onsemi",              "industry": "Semiconductor / Hardware",
     "career_url": "https://www.onsemi.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/onsemi/jobs/"},
    {"name": "Skyworks Solutions",  "industry": "Semiconductor / Hardware",
     "career_url": "https://www.skyworksinc.com/en/Careers",
     "linkedin_url": "https://www.linkedin.com/company/skyworks-solutions/jobs/"},
    {"name": "GlobalFoundries",     "industry": "Semiconductor / Hardware",
     "career_url": "https://gf.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/globalfoundries/jobs/"},
    {"name": "Samsung Semiconductor", "industry": "Semiconductor / Hardware",
     "career_url": "https://semiconductor.samsung.com/us/careers/",
     "linkedin_url": "https://www.linkedin.com/company/samsung-semiconductor/jobs/"},

    # ── Day 3: Aerospace / Defense / Automotive ─────────────────────────
    {"name": "Boeing",              "industry": "Aerospace / Defense / Auto",
     "career_url": "https://jobs.boeing.com/",
     "linkedin_url": "https://www.linkedin.com/company/boeing/jobs/"},
    {"name": "Lockheed Martin",     "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.lockheedmartinjobs.com/",
     "linkedin_url": "https://www.linkedin.com/company/lockheed-martin/jobs/"},
    {"name": "Northrop Grumman",    "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.northropgrumman.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/northrop-grumman/jobs/"},
    {"name": "RTX",                 "industry": "Aerospace / Defense / Auto",
     "career_url": "https://rtx.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/rtx/jobs/"},
    {"name": "General Dynamics",    "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.gd.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/general-dynamics/jobs/"},
    {"name": "L3Harris Technologies", "industry": "Aerospace / Defense / Auto",
     "career_url": "https://careers.l3harris.com/",
     "linkedin_url": "https://www.linkedin.com/company/l3harris-technologies/jobs/"},
    {"name": "SpaceX",              "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.spacex.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/spacex/jobs/"},
    {"name": "Blue Origin",         "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.blueorigin.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/blue-origin/jobs/"},
    {"name": "Anduril Industries",  "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.anduril.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/anduril-industries/jobs/"},
    {"name": "Tesla",               "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.tesla.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/tesla-motors/jobs/"},
    {"name": "Rivian",              "industry": "Aerospace / Defense / Auto",
     "career_url": "https://rivian.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/rivian/jobs/"},
    {"name": "Zoox",                "industry": "Aerospace / Defense / Auto",
     "career_url": "https://zoox.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/zoox/jobs/"},
    {"name": "Waymo",               "industry": "Aerospace / Defense / Auto",
     "career_url": "https://waymo.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/waymo/jobs/"},
    {"name": "Cruise",              "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.getcruise.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/getcruise/jobs/"},
    {"name": "Ford Motor Company",  "industry": "Aerospace / Defense / Auto",
     "career_url": "https://corporate.ford.com/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/ford-motor-company/jobs/"},
    {"name": "General Motors",      "industry": "Aerospace / Defense / Auto",
     "career_url": "https://search-careers.gm.com/",
     "linkedin_url": "https://www.linkedin.com/company/general-motors/jobs/"},
    {"name": "John Deere",          "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.deere.com/en/our-company/careers/",
     "linkedin_url": "https://www.linkedin.com/company/john-deere/jobs/"},
    {"name": "Caterpillar",         "industry": "Aerospace / Defense / Auto",
     "career_url": "https://careers.caterpillar.com/",
     "linkedin_url": "https://www.linkedin.com/company/caterpillar-inc-/jobs/"},
    {"name": "Collins Aerospace",   "industry": "Aerospace / Defense / Auto",
     "career_url": "https://www.collinsaerospace.com/who-we-are/careers",
     "linkedin_url": "https://www.linkedin.com/company/collins-aerospace/jobs/"},
    {"name": "Garmin",              "industry": "Aerospace / Defense / Auto",
     "career_url": "https://careers.garmin.com/",
     "linkedin_url": "https://www.linkedin.com/company/garmin/jobs/"},

    # ── Day 4: Quant Trading / Fintech ──────────────────────────────────
    {"name": "Jane Street",         "industry": "Quant Trading / Fintech",
     "career_url": "https://www.janestreet.com/join-jane-street/",
     "linkedin_url": "https://www.linkedin.com/company/jane-street/jobs/"},
    {"name": "Citadel",             "industry": "Quant Trading / Fintech",
     "career_url": "https://www.citadel.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/citadel-llc/jobs/"},
    {"name": "Citadel Securities",  "industry": "Quant Trading / Fintech",
     "career_url": "https://www.citadelsecurities.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/citadel-securities/jobs/"},
    {"name": "DRW",                 "industry": "Quant Trading / Fintech",
     "career_url": "https://drw.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/drw-trading-group/jobs/"},
    {"name": "Jump Trading",        "industry": "Quant Trading / Fintech",
     "career_url": "https://www.jumptrading.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/jump-trading/jobs/"},
    {"name": "Susquehanna (SIG)",   "industry": "Quant Trading / Fintech",
     "career_url": "https://careers.sig.com/",
     "linkedin_url": "https://www.linkedin.com/company/susquehanna-international-group/jobs/"},
    {"name": "Akuna Capital",       "industry": "Quant Trading / Fintech",
     "career_url": "https://akunacapital.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/akuna-capital/jobs/"},
    {"name": "Two Sigma",           "industry": "Quant Trading / Fintech",
     "career_url": "https://www.twosigma.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/two-sigma-investments/jobs/"},
    {"name": "Hudson River Trading", "industry": "Quant Trading / Fintech",
     "career_url": "https://www.hudsonrivertrading.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/hudson-river-trading/jobs/"},
    {"name": "Optiver",             "industry": "Quant Trading / Fintech",
     "career_url": "https://optiver.com/working-at-optiver/career-opportunities/",
     "linkedin_url": "https://www.linkedin.com/company/optiver/jobs/"},
    {"name": "Goldman Sachs",       "industry": "Quant Trading / Fintech",
     "career_url": "https://www.goldmansachs.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/goldman-sachs/jobs/"},
    {"name": "JPMorgan Chase",      "industry": "Quant Trading / Fintech",
     "career_url": "https://careers.jpmorgan.com/",
     "linkedin_url": "https://www.linkedin.com/company/jpmorganchase/jobs/"},
    {"name": "Morgan Stanley",      "industry": "Quant Trading / Fintech",
     "career_url": "https://www.morganstanley.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/morgan-stanley/jobs/"},
    {"name": "Capital One",         "industry": "Quant Trading / Fintech",
     "career_url": "https://www.capitalonecareers.com/",
     "linkedin_url": "https://www.linkedin.com/company/capital-one/jobs/"},
    {"name": "Discover Financial Services", "industry": "Quant Trading / Fintech",
     "career_url": "https://jobs.discover.com/",
     "linkedin_url": "https://www.linkedin.com/company/discover-financial-services/jobs/"},
    {"name": "Visa",                "industry": "Quant Trading / Fintech",
     "career_url": "https://corporate.visa.com/en/jobs.html",
     "linkedin_url": "https://www.linkedin.com/company/visa/jobs/"},
    {"name": "Mastercard",          "industry": "Quant Trading / Fintech",
     "career_url": "https://careers.mastercard.com/",
     "linkedin_url": "https://www.linkedin.com/company/mastercard/jobs/"},
    {"name": "Bloomberg LP",        "industry": "Quant Trading / Fintech",
     "career_url": "https://careers.bloomberg.com/",
     "linkedin_url": "https://www.linkedin.com/company/bloomberg/jobs/"},
    {"name": "Stripe",              "industry": "Quant Trading / Fintech",
     "career_url": "https://stripe.com/jobs",
     "linkedin_url": "https://www.linkedin.com/company/stripe/jobs/"},
    {"name": "PayPal",              "industry": "Quant Trading / Fintech",
     "career_url": "https://careers.pypl.com/",
     "linkedin_url": "https://www.linkedin.com/company/paypal/jobs/"},

    # ── Day 5: Illinois-region + AI / misc ──────────────────────────────
    {"name": "State Farm",          "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.statefarm.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/state-farm/jobs/"},
    {"name": "Allstate",            "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.allstate.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/allstate/jobs/"},
    {"name": "Motorola Solutions",  "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.motorolasolutions.com/",
     "linkedin_url": "https://www.linkedin.com/company/motorola-solutions/jobs/"},
    {"name": "Epic Systems",        "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.epic.com/",
     "linkedin_url": "https://www.linkedin.com/company/epic/jobs/"},
    {"name": "Grainger",            "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.grainger.com/",
     "linkedin_url": "https://www.linkedin.com/company/grainger/jobs/"},
    {"name": "Abbott Laboratories", "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.jobs.abbott/",
     "linkedin_url": "https://www.linkedin.com/company/abbott/jobs/"},
    {"name": "AbbVie",              "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.abbvie.com/",
     "linkedin_url": "https://www.linkedin.com/company/abbvie/jobs/"},
    {"name": "United Airlines",     "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.united.com/",
     "linkedin_url": "https://www.linkedin.com/company/united-airlines/jobs/"},
    {"name": "Northern Trust",      "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.northerntrust.com/",
     "linkedin_url": "https://www.linkedin.com/company/northern-trust/jobs/"},
    {"name": "CME Group",           "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.cmegroup.com/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/cme-group/jobs/"},
    {"name": "ByteDance (TikTok)",  "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.tiktok.com/",
     "linkedin_url": "https://www.linkedin.com/company/tiktok/jobs/"},
    {"name": "Palantir Technologies", "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.palantir.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/palantir-technologies/jobs/"},
    {"name": "Databricks",          "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.databricks.com/company/careers",
     "linkedin_url": "https://www.linkedin.com/company/databricks/jobs/"},
    {"name": "Anthropic",           "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.anthropic.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/anthropicresearch/jobs/"},
    {"name": "OpenAI",              "industry": "Illinois Region / AI / Misc",
     "career_url": "https://openai.com/careers/",
     "linkedin_url": "https://www.linkedin.com/company/openai/jobs/"},
    {"name": "Zoom",                "industry": "Illinois Region / AI / Misc",
     "career_url": "https://careers.zoom.us/",
     "linkedin_url": "https://www.linkedin.com/company/zoom-video-communications/jobs/"},
    {"name": "Atlassian",           "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.atlassian.com/company/careers",
     "linkedin_url": "https://www.linkedin.com/company/atlassian/jobs/"},
    {"name": "Workday",             "industry": "Illinois Region / AI / Misc",
     "career_url": "https://workday.wd5.myworkdayjobs.com/Workday",
     "linkedin_url": "https://www.linkedin.com/company/workday/jobs/"},
    {"name": "Splunk",              "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.splunk.com/en_us/careers.html",
     "linkedin_url": "https://www.linkedin.com/company/splunk/jobs/"},
    {"name": "Nutanix",             "industry": "Illinois Region / AI / Misc",
     "career_url": "https://www.nutanix.com/careers",
     "linkedin_url": "https://www.linkedin.com/company/nutanix/jobs/"},
]
